// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDjkJqAC_FutTKjDUkkNhGThrtKbSjSDM',
    appId: '1:820952193597:web:fd15e2230e9c3b2726a854',
    messagingSenderId: '820952193597',
    projectId: 'iti-front-qena2-2cbb2',
    authDomain: 'iti-front-qena2-2cbb2.firebaseapp.com',
    storageBucket: 'iti-front-qena2-2cbb2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMSq2r7AQMzNuQdsRGZsJaZhkIi7ALC_I',
    appId: '1:820952193597:android:b09f37af9261f08226a854',
    messagingSenderId: '820952193597',
    projectId: 'iti-front-qena2-2cbb2',
    storageBucket: 'iti-front-qena2-2cbb2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6ICwnlIBIdJCXCKr4uqq243aT9GGEzjE',
    appId: '1:820952193597:ios:4eaa1b141ad2adcd26a854',
    messagingSenderId: '820952193597',
    projectId: 'iti-front-qena2-2cbb2',
    storageBucket: 'iti-front-qena2-2cbb2.appspot.com',
    iosClientId: '820952193597-0sjbega35ttq5bm0dc2lie14amae8jnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6ICwnlIBIdJCXCKr4uqq243aT9GGEzjE',
    appId: '1:820952193597:ios:4eaa1b141ad2adcd26a854',
    messagingSenderId: '820952193597',
    projectId: 'iti-front-qena2-2cbb2',
    storageBucket: 'iti-front-qena2-2cbb2.appspot.com',
    iosClientId: '820952193597-0sjbega35ttq5bm0dc2lie14amae8jnk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todoList',
  );
}
